/* eslint-disable @typescript-eslint/no-explicit-any */
import {
  useEffect,
  useMemo,
  useRef,
  useState,
  type ChangeEvent,
  type FormEvent,
} from "react";

import {
  PackLocationPicker,
  PackLocationsMap,
  type PackMapMarker,
  type PackMapPoint,
} from "../../components/PackLocationPicker";
import {
  csvRowsToObjects,
  downloadCsv,
  parseCsvRows,
  sanitizeCsvFilename,
  type CsvCell,
} from "../../lib/csv";

type Props = any;

const packCsvColumns = [
  "pack_uuid",
  "name",
  "description",
  "active",
  "spot_count",
  "latitude",
  "longitude",
  "campus_id",
  "spots_with_qr",
] as const;

function parseMapPoint(lat: string, lng: string): PackMapPoint | null {
  const parsedLat = Number(lat.trim());
  const parsedLng = Number(lng.trim());
  if (!Number.isFinite(parsedLat) || !Number.isFinite(parsedLng)) {
    return null;
  }

  return {
    lat: parsedLat,
    lng: parsedLng,
  };
}

export function PacksScreen(props: Props) {
  const {
    activeSchoolId,
    packBusy,
    packsLoading,
    activePackTab,
    setActivePackTab,
    refreshSchoolPacks,
    schoolPacks,
    existingPackMapMarkers,
    packsWithoutLocationsCount,
    handleCreatePack,
    handleCreatePackDraft,
    packDraft,
    setPackDraft,
    schoolDraft,
    packPhotoPreviewUrl,
    EntityImagePreview,
    packPhotoFile,
    handlePackPhotoFileChange,
    setPackPhotoFile,
    setPackPhotoPreviewUrl,
    resetPackCreateForm,
    selectedPackLocation,
    handlePackLocationSelect,
    editingPackId,
    packEditDraft,
    getPackPhotoUrl,
    packEditPhotoPreviewUrl,
    handleCancelPackEdit,
    handleStartEditingPack,
    packEditBusy,
    handleDownloadPackQrCode,
    qrActionTarget,
    handleGeneratePackQrCode,
    handleDownloadPackSpotQrCode,
    handleGeneratePackSpotQrCode,
    handleSavePackEdit,
    setPackEditDraft,
    packEditPhotoFile,
    handlePackEditPhotoFileChange,
    setPackEditPhotoFile,
    setPackEditPhotoPreviewUrl,
    UuidCopyField,
    handleCopyUuid,
  } = props;
  const [isImportModalOpen, setIsImportModalOpen] = useState(false);
  const [pendingImportedPacks, setPendingImportedPacks] = useState<any[]>([]);
  const [importMessage, setImportMessage] = useState("");
  const autoGeneratedPackQrRef = useRef<Set<string>>(new Set());
  const [packEditSnapshot, setPackEditSnapshot] = useState<any>(null);
  const packEditSnapshotIdRef = useRef("");

  useEffect(() => {
    if (!editingPackId) {
      packEditSnapshotIdRef.current = "";
      setPackEditSnapshot(null);
      return;
    }
    if (editingPackId !== packEditSnapshotIdRef.current && packEditDraft) {
      packEditSnapshotIdRef.current = editingPackId;
      setPackEditSnapshot(packEditDraft);
    }
  }, [editingPackId, packEditDraft]);

  const isPackEditDirty =
    !!packEditDraft &&
    !!packEditSnapshot &&
    (JSON.stringify(packEditDraft) !== JSON.stringify(packEditSnapshot) ||
      !!packEditPhotoFile);

  function discardPackEditChanges() {
    if (packEditSnapshot) {
      setPackEditDraft(packEditSnapshot);
    }
    setPackEditPhotoFile(null);
    setPackEditPhotoPreviewUrl("");
  }

  useEffect(() => {
    for (const pack of schoolPacks as any[]) {
      if (
        !pack.pack_uuid ||
        pack.qr_code ||
        autoGeneratedPackQrRef.current.has(pack.pack_uuid) ||
        qrActionTarget === `pack:${pack.pack_uuid}`
      ) {
        continue;
      }
      autoGeneratedPackQrRef.current.add(pack.pack_uuid);
      void handleGeneratePackQrCode(pack);
    }
  }, [schoolPacks, qrActionTarget, handleGeneratePackQrCode]);

  const editingPack = useMemo(
    () =>
      editingPackId
        ? (schoolPacks.find((pack: any) => pack.pack_uuid === editingPackId) ??
          null)
        : null,
    [editingPackId, schoolPacks],
  );
  const editPackLocation = packEditDraft
    ? parseMapPoint(packEditDraft.lat, packEditDraft.lng)
    : null;
  const editOtherMarkers: PackMapMarker[] = editingPack
    ? existingPackMapMarkers.filter(
        (marker: PackMapMarker) => marker.id !== editingPack.pack_uuid,
      )
    : existingPackMapMarkers;

  function openCreateModal() {
    setActivePackTab("create");
  }

  function closeCreateModal() {
    setActivePackTab("existing");
  }

  function downloadPacksCsv() {
    const rows = schoolPacks.map((pack: any) => {
      const spotsWithQr = pack.spots.filter((spot: any) => spot.qr_code).length;
      return [
        pack.pack_uuid,
        pack.name,
        pack.description,
        pack.active,
        pack.spot_count,
        pack.location?.lat ?? "",
        pack.location?.lng ?? "",
        pack.school_owner?.campus_id ?? "",
        spotsWithQr,
      ] satisfies CsvCell[];
    });

    downloadCsv(
      sanitizeCsvFilename(
        `${activeSchoolId || "school"}-juise-packs`,
        "juise-packs",
      ),
      [packCsvColumns, ...rows],
    );
  }

  function buildPackDraftFromCsvRow(row: Record<string, string>) {
    return {
      ...packDraft,
      name: row.name ?? row.pack_name ?? "",
      description: row.description ?? "",
      number_of_spots:
        row.number_of_spots ?? row.spot_count ?? packDraft.number_of_spots,
      campus_id:
        row.campus_id ??
        row.campus ??
        schoolDraft.default_campus_id ??
        packDraft.campus_id,
      lat: row.latitude ?? row.lat ?? "",
      lng: row.longitude ?? row.lng ?? "",
    };
  }

  function openImportModal() {
    setPendingImportedPacks([]);
    setImportMessage("");
    setIsImportModalOpen(true);
  }

  async function handlePackCsvUpload(event: ChangeEvent<HTMLInputElement>) {
    const file = event.target.files?.[0];
    event.target.value = "";
    if (!file) {
      return;
    }

    const imported = csvRowsToObjects(parseCsvRows(await file.text()))
      .map(buildPackDraftFromCsvRow)
      .filter(
        (draft) =>
          draft.name.trim() ||
          draft.description.trim() ||
          draft.lat.trim() ||
          draft.lng.trim(),
      );
    if (imported.length === 0) {
      setImportMessage("No pack rows were found in that CSV.");
      setPendingImportedPacks([]);
      return;
    }

    setPendingImportedPacks(imported);
    setImportMessage(
      `Loaded ${imported.length} pack${imported.length === 1 ? "" : "s"} from the CSV.`,
    );
  }

  async function applyPackImport() {
    if (pendingImportedPacks.length === 0) {
      setImportMessage("Choose a CSV with at least one valid pack row first.");
      return;
    }

    for (const draft of pendingImportedPacks) {
      const didCreate = await handleCreatePackDraft(draft, null);
      if (!didCreate) {
        return;
      }
    }

    setPendingImportedPacks([]);
    setImportMessage("");
    setIsImportModalOpen(false);
  }

  function handleEditLocationSelect(point: PackMapPoint) {
    setPackEditDraft((current: any) =>
      current
        ? {
            ...current,
            lat: point.lat.toFixed(6),
            lng: point.lng.toFixed(6),
          }
        : current,
    );
  }

  function submitCreatePack(event: FormEvent<HTMLFormElement>) {
    void handleCreatePack(event);
  }

  function submitEditPack(event: FormEvent<HTMLFormElement>, pack: any) {
    void handleSavePackEdit(event, pack);
  }

  return (
    <section className="panel management-page">
      <div className="panel-header">
        <div>
          <p className="eyebrow">Juise Packs</p>
          <h2>School-owned parking packs</h2>
        </div>
        <div className="management-actions">
          <button
            className="secondary-button"
            type="button"
            onClick={downloadPacksCsv}
            disabled={schoolPacks.length === 0}
          >
            Download CSV
          </button>
          <button
            className="secondary-button"
            type="button"
            onClick={openImportModal}
            disabled={!activeSchoolId || packBusy}
          >
            Upload CSV
          </button>
          <button
            className="secondary-button"
            type="button"
            onClick={() => void refreshSchoolPacks()}
            disabled={packsLoading || !activeSchoolId}
          >
            Reload
          </button>
          <button
            className="primary-button"
            type="button"
            onClick={openCreateModal}
            disabled={!activeSchoolId}
            aria-label="Add Juise Pack"
          >
            +
          </button>
        </div>
      </div>

      {!activeSchoolId ? (
        <p className="empty-state">
          This admin login is not scoped to a school.
        </p>
      ) : null}

      {importMessage ? <p className="empty-state">{importMessage}</p> : null}

      {activeSchoolId ? (
        <>
          <div className="management-summary-grid">
            <div className="reports-kpi">
              <span>Total Packs</span>
              <strong>{schoolPacks.length}</strong>
            </div>
            <div className="reports-kpi">
              <span>Located</span>
              <strong>{existingPackMapMarkers.length}</strong>
            </div>
            <div className="reports-kpi">
              <span>No Location</span>
              <strong>{packsWithoutLocationsCount}</strong>
            </div>
          </div>

          <div className="management-map-card">
            <div className="data-section-header">
              <div>
                <h3>Pack map</h3>
                <p className="muted-text">
                  Markers show saved Juise Pack locations for this school.
                </p>
              </div>
              <span>{existingPackMapMarkers.length} pins</span>
            </div>
            <PackLocationsMap
              markers={existingPackMapMarkers}
              onEditMarker={(packId) => {
                const pack = (schoolPacks as any[]).find(
                  (candidate) => candidate.pack_uuid === packId,
                );
                if (pack) {
                  handleStartEditingPack(pack);
                }
              }}
            />
            {packsWithoutLocationsCount > 0 ? (
              <p className="muted-text">
                {packsWithoutLocationsCount} pack
                {packsWithoutLocationsCount === 1 ? "" : "s"} do not have saved
                coordinates yet.
              </p>
            ) : null}
          </div>

          <div className="management-table-card">
            <div className="data-section-header">
              <div>
                <h3>Created packs</h3>
                <p className="muted-text">
                  Open a row to edit pack details or manage QR codes.
                </p>
              </div>
              {packBusy || packsLoading ? (
                <span className="muted-text">
                  {packBusy ? "Creating..." : "Refreshing..."}
                </span>
              ) : null}
            </div>

            {packsLoading && schoolPacks.length === 0 ? (
              <p className="muted-text">Loading school packs...</p>
            ) : null}

            {!packsLoading && schoolPacks.length === 0 ? (
              <p className="empty-state">
                No school-owned Juise packs have been created yet.
              </p>
            ) : null}

            {schoolPacks.length > 0 ? (
              <div className="management-table-scroll">
                <table className="management-table">
                  <thead>
                    <tr>
                      <th>Pack</th>
                      <th>Campus</th>
                      <th>Spots</th>
                      <th>Location</th>
                      <th>QR</th>
                      <th>Actions</th>
                    </tr>
                  </thead>
                  <tbody>
                    {schoolPacks.map((pack: any) => {
                      return (
                        <tr key={pack.pack_uuid}>
                          <td>
                            <strong>{pack.name || "Juise Pack"}</strong>
                            <span>{pack.description || "No description"}</span>
                          </td>
                          <td>{pack.school_owner?.campus_id || "-"}</td>
                          <td>{pack.spot_count} total</td>
                          <td>
                            {pack.location
                              ? `${pack.location.lat.toFixed(6)}, ${pack.location.lng.toFixed(6)}`
                              : "No location"}
                          </td>
                          <td>
                            {pack.qr_code ? (
                              <button
                                className="secondary-button"
                                type="button"
                                onClick={() => handleDownloadPackQrCode(pack)}
                              >
                                Download
                              </button>
                            ) : (
                              <button
                                className="secondary-button"
                                type="button"
                                onClick={() =>
                                  void handleGeneratePackQrCode(pack)
                                }
                                disabled={
                                  qrActionTarget === `pack:${pack.pack_uuid}`
                                }
                              >
                                {qrActionTarget === `pack:${pack.pack_uuid}`
                                  ? "Generating..."
                                  : "Generate"}
                              </button>
                            )}
                          </td>
                          <td>
                            <button
                              className="secondary-button"
                              type="button"
                              onClick={() => handleStartEditingPack(pack)}
                              disabled={packEditBusy}
                            >
                              Edit
                            </button>
                          </td>
                        </tr>
                      );
                    })}
                  </tbody>
                </table>
              </div>
            ) : null}
          </div>
        </>
      ) : null}

      {isImportModalOpen ? (
        <div
          className="management-modal-backdrop"
          role="dialog"
          aria-modal="true"
          aria-label="Upload Juise Packs CSV"
          onClick={() => setIsImportModalOpen(false)}
        >
          <div
            className="management-modal-sheet management-import-modal"
            onClick={(event) => event.stopPropagation()}
          >
            <div className="management-modal-header">
              <div>
                <p className="eyebrow">CSV upload</p>
                <h3>Import Juise Packs</h3>
              </div>
              <button
                className="text-button management-modal-close"
                type="button"
                onClick={() => setIsImportModalOpen(false)}
              >
                Close
              </button>
            </div>

            <div className="management-import-body">
              <div className="management-import-instructions">
                <h4>Required CSV headers</h4>
                <code>
                  name,description,number_of_spots,latitude,longitude,campus_id
                </code>
                <p className="muted-text">
                  <code>campus_id</code> is optional if the school has a default
                  campus. Latitude and longitude must be decimal coordinates.
                  Photos and QR codes are not imported from CSV.
                </p>
              </div>

              <label className="secondary-button challenge-upload-button management-import-upload">
                <input
                  className="challenge-upload-input"
                  type="file"
                  accept=".csv,text/csv"
                  onChange={(event) => void handlePackCsvUpload(event)}
                  disabled={packBusy}
                />
                Choose CSV
              </label>

              {importMessage ? (
                <p className="empty-state">{importMessage}</p>
              ) : null}

              {pendingImportedPacks.length > 0 ? (
                <div className="management-table-scroll">
                  <table className="management-table">
                    <thead>
                      <tr>
                        <th>Name</th>
                        <th>Spots</th>
                        <th>Campus</th>
                        <th>Latitude</th>
                        <th>Longitude</th>
                      </tr>
                    </thead>
                    <tbody>
                      {pendingImportedPacks.slice(0, 8).map((draft, index) => (
                        <tr key={`${draft.name}-${index}`}>
                          <td>
                            <strong>{draft.name || `Pack ${index + 1}`}</strong>
                            <span>{draft.description || "No description"}</span>
                          </td>
                          <td>{draft.number_of_spots || "1"}</td>
                          <td>{draft.campus_id || "-"}</td>
                          <td>{draft.lat || "-"}</td>
                          <td>{draft.lng || "-"}</td>
                        </tr>
                      ))}
                    </tbody>
                  </table>
                </div>
              ) : null}

              <div className="form-actions">
                <button
                  className="secondary-button"
                  type="button"
                  onClick={() => setIsImportModalOpen(false)}
                  disabled={packBusy}
                >
                  Cancel
                </button>
                <button
                  className="primary-button"
                  type="button"
                  onClick={() => void applyPackImport()}
                  disabled={packBusy || pendingImportedPacks.length === 0}
                >
                  {packBusy ? "Creating..." : "Done"}
                </button>
              </div>
            </div>
          </div>
        </div>
      ) : null}

      {activePackTab === "create" ? (
        <div
          className="management-modal-backdrop"
          role="dialog"
          aria-modal="true"
          aria-label="Create Juise Pack"
          onClick={closeCreateModal}
        >
          <form
            className="management-modal-sheet"
            onSubmit={submitCreatePack}
            onClick={(event) => event.stopPropagation()}
          >
            <div className="management-modal-header">
              <div>
                <p className="eyebrow">New Juise Pack</p>
                <h3>{packDraft.name || "Create pack"}</h3>
              </div>
              <button
                className="text-button management-modal-close"
                type="button"
                onClick={closeCreateModal}
              >
                Close
              </button>
            </div>

            <div className="management-modal-grid">
              <div className="management-modal-map">
                <PackLocationPicker
                  disabled={!activeSchoolId}
                  onChange={handlePackLocationSelect}
                  value={selectedPackLocation}
                  otherMarkers={existingPackMapMarkers}
                />
              </div>

              <div className="data-section">
                <div className="form-grid">
                  <label className="field">
                    <span>Campus ID</span>
                    <input
                      value={packDraft.campus_id}
                      onChange={(event) =>
                        setPackDraft((current: any) => ({
                          ...current,
                          campus_id: event.target.value,
                        }))
                      }
                      placeholder={schoolDraft.default_campus_id || "main"}
                      disabled={!activeSchoolId}
                    />
                  </label>
                  <label className="field">
                    <span>Number of Spots</span>
                    <input
                      type="number"
                      min={1}
                      value={packDraft.number_of_spots}
                      onChange={(event) =>
                        setPackDraft((current: any) => ({
                          ...current,
                          number_of_spots: event.target.value,
                        }))
                      }
                      disabled={!activeSchoolId}
                    />
                  </label>
                  <label className="field">
                    <span>Pack Name</span>
                    <input
                      value={packDraft.name}
                      onChange={(event) =>
                        setPackDraft((current: any) => ({
                          ...current,
                          name: event.target.value,
                        }))
                      }
                      placeholder="North Garage Pack"
                      disabled={!activeSchoolId}
                    />
                  </label>
                  <label className="field">
                    <span>Latitude</span>
                    <input
                      value={packDraft.lat}
                      onChange={(event) =>
                        setPackDraft((current: any) => ({
                          ...current,
                          lat: event.target.value,
                        }))
                      }
                      placeholder="42.678000"
                      disabled={!activeSchoolId}
                    />
                  </label>
                  <label className="field">
                    <span>Longitude</span>
                    <input
                      value={packDraft.lng}
                      onChange={(event) =>
                        setPackDraft((current: any) => ({
                          ...current,
                          lng: event.target.value,
                        }))
                      }
                      placeholder="-83.195000"
                      disabled={!activeSchoolId}
                    />
                  </label>
                  <label className="field field-span-2">
                    <span>Description</span>
                    <textarea
                      value={packDraft.description}
                      onChange={(event) =>
                        setPackDraft((current: any) => ({
                          ...current,
                          description: event.target.value,
                        }))
                      }
                      placeholder="Covered student parking near the library entrance."
                      rows={4}
                      disabled={!activeSchoolId}
                    />
                  </label>
                  <div className="field field-span-2">
                    <span>Cover Photo</span>
                    <div className="challenge-image-field">
                      <EntityImagePreview
                        imageUrl={packPhotoPreviewUrl}
                        label={packDraft.name || "Juise Pack"}
                        altSuffix="pack photo"
                        fallbackLabel="Pack photo"
                      />
                      <div className="challenge-image-field-controls">
                        <div className="challenge-image-upload-row">
                          <label className="secondary-button challenge-upload-button">
                            <input
                              className="challenge-upload-input"
                              type="file"
                              accept="image/png,image/jpeg,image/webp,image/gif"
                              onChange={handlePackPhotoFileChange}
                              disabled={packBusy || !activeSchoolId}
                            />
                            {packPhotoFile ? "Replace Photo" : "Upload Photo"}
                          </label>
                          {packPhotoFile ? (
                            <button
                              className="secondary-button"
                              type="button"
                              onClick={() => {
                                setPackPhotoFile(null);
                                setPackPhotoPreviewUrl("");
                              }}
                              disabled={packBusy}
                            >
                              Clear Photo
                            </button>
                          ) : null}
                        </div>
                      </div>
                    </div>
                  </div>
                </div>

                <div className="form-actions">
                  <button
                    className="secondary-button"
                    type="button"
                    disabled={packBusy}
                    onClick={() =>
                      resetPackCreateForm(schoolDraft.default_campus_id ?? "")
                    }
                  >
                    Reset
                  </button>
                  <button
                    className="primary-button"
                    type="submit"
                    disabled={packBusy || !activeSchoolId}
                  >
                    {packBusy ? "Creating..." : "Create Pack"}
                  </button>
                </div>
              </div>
            </div>
          </form>
        </div>
      ) : null}

      {editingPack && packEditDraft ? (
        <div
          className="management-modal-backdrop"
          role="dialog"
          aria-modal="true"
          aria-label="Edit Juise Pack"
          onClick={handleCancelPackEdit}
        >
          <form
            className="management-modal-sheet"
            onSubmit={(event) => submitEditPack(event, editingPack)}
            onClick={(event) => event.stopPropagation()}
          >
            <div className="management-modal-header">
              <div>
                <p className="eyebrow">Pack editor</p>
                <h3>
                  {packEditDraft.name || editingPack.name || "Juise Pack"}
                </h3>
              </div>
              <button
                className="text-button management-modal-close"
                type="button"
                onClick={handleCancelPackEdit}
              >
                Close
              </button>
            </div>

            <div className="management-modal-grid">
              <div className="management-modal-map">
                <PackLocationPicker
                  disabled={packEditBusy}
                  onChange={handleEditLocationSelect}
                  value={editPackLocation}
                  otherMarkers={editOtherMarkers}
                />

                {editingPack.spots.length > 0 ? (
                  <div className="pack-spots-chips management-spot-list">
                    {editingPack.spots.map((spot: any) => (
                      <div className="pack-spot-chip" key={spot.spot_uuid}>
                        <span className="pack-spot-chip-num">
                          #{spot.spot_number}
                        </span>
                        {spot.qr_code ? (
                          <button
                            className="pack-spot-qr-button pack-spot-chip-qr pack-spot-chip-qr-ready"
                            type="button"
                            onClick={() => handleDownloadPackSpotQrCode(spot)}
                            title="Download QR for this spot"
                          >
                            QR
                          </button>
                        ) : (
                          <button
                            className="pack-spot-qr-button pack-spot-chip-qr"
                            type="button"
                            onClick={() =>
                              void handleGeneratePackSpotQrCode(spot)
                            }
                            disabled={
                              qrActionTarget === `spot:${spot.spot_uuid}`
                            }
                            title="Generate QR for this spot"
                          >
                            {qrActionTarget === `spot:${spot.spot_uuid}`
                              ? "..."
                              : "+ QR"}
                          </button>
                        )}
                      </div>
                    ))}
                  </div>
                ) : null}
              </div>

              <div className="data-section">
                <div className="form-grid">
                  <label className="field">
                    <span>Pack Name</span>
                    <input
                      value={packEditDraft.name}
                      onChange={(event) =>
                        setPackEditDraft((current: any) =>
                          current
                            ? { ...current, name: event.target.value }
                            : current,
                        )
                      }
                      placeholder="North Garage Pack"
                      disabled={packEditBusy}
                    />
                  </label>
                  <label className="field">
                    <span>Latitude</span>
                    <input
                      value={packEditDraft.lat}
                      onChange={(event) =>
                        setPackEditDraft((current: any) =>
                          current
                            ? { ...current, lat: event.target.value }
                            : current,
                        )
                      }
                      placeholder="42.678000"
                      disabled={packEditBusy}
                    />
                  </label>
                  <label className="field">
                    <span>Longitude</span>
                    <input
                      value={packEditDraft.lng}
                      onChange={(event) =>
                        setPackEditDraft((current: any) =>
                          current
                            ? { ...current, lng: event.target.value }
                            : current,
                        )
                      }
                      placeholder="-83.195000"
                      disabled={packEditBusy}
                    />
                  </label>
                  <label className="field field-span-2">
                    <span>Description</span>
                    <textarea
                      value={packEditDraft.description}
                      onChange={(event) =>
                        setPackEditDraft((current: any) =>
                          current
                            ? { ...current, description: event.target.value }
                            : current,
                        )
                      }
                      placeholder="Covered student parking near the library entrance."
                      rows={4}
                      disabled={packEditBusy}
                    />
                  </label>
                  <div className="field field-span-2">
                    <span>Pack Photo</span>
                    <div className="challenge-image-field">
                      <EntityImagePreview
                        imageUrl={
                          packEditPhotoPreviewUrl ||
                          getPackPhotoUrl(editingPack)
                        }
                        label={editingPack.name || "Juise Pack"}
                        altSuffix="pack photo"
                        fallbackLabel="Pack photo preview"
                      />
                      <div className="challenge-image-field-controls">
                        <div className="challenge-image-upload-row">
                          <label className="secondary-button challenge-upload-button">
                            <input
                              className="challenge-upload-input"
                              type="file"
                              accept="image/png,image/jpeg,image/webp,image/gif"
                              onChange={handlePackEditPhotoFileChange}
                              disabled={packEditBusy}
                            />
                            {packEditPhotoFile
                              ? "Replace Photo"
                              : "Upload Photo"}
                          </label>
                          {packEditPhotoFile ? (
                            <button
                              className="secondary-button"
                              type="button"
                              onClick={() => {
                                setPackEditPhotoFile(null);
                                setPackEditPhotoPreviewUrl("");
                              }}
                              disabled={packEditBusy}
                            >
                              Use Current Photo
                            </button>
                          ) : null}
                        </div>
                      </div>
                    </div>
                  </div>
                </div>

                <div className="uuid-copy-stack">
                  <UuidCopyField
                    label="pack_uuid"
                    value={editingPack.pack_uuid}
                    onCopy={handleCopyUuid}
                  />
                </div>

                <div className="form-actions">
                  <button
                    className="secondary-button"
                    type="button"
                    onClick={handleCancelPackEdit}
                    disabled={packEditBusy}
                  >
                    Cancel
                  </button>
                  <button
                    className="secondary-button"
                    type="button"
                    onClick={discardPackEditChanges}
                    disabled={packEditBusy || !isPackEditDirty}
                    title="Discard unsaved changes"
                  >
                    ✕ Discard changes
                  </button>
                  <button
                    className="primary-button"
                    type="submit"
                    disabled={packEditBusy || !isPackEditDirty}
                  >
                    {packEditBusy ? "Saving..." : "Save"}
                  </button>
                </div>
              </div>
            </div>
          </form>
        </div>
      ) : null}
    </section>
  );
}
